FROM alpine
ADD build.tar.gz /
RUN adduser -S www-data
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default /etc/nginx/sites-enabled/default
COPY php/php.ini /$PHP_PATH/usr/etc/php.ini
COPY php/www.conf $PHP_PATH/etc/php-fpm.d/www.conf
COPY php/php-fpm.conf $PHP_PATH/etc/php-fpm.conf

ENV PATH=$PATH:$PHP_PATH

#Set up services
COPY php/php-fpm /etc/init.d/php-fpm
RUN chmod 755 /etc/init.d/php-fpm
RUN chown root:root /etc/init.d/php-fpm
